#version: "3"
#services:
#  server:
#    image: backend
#    ports:
#      - "8080:8080"
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysql_server:3306/bibliotheque_db
#    networks:
#      - bibliotheque_mysql_net
#    depends_on:
#      - mysql_server
#
#  mysqldb:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_USER=root
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=bibliotheque_db
#    networks:
#      - bibliotheque_mysql_net
#
#networks:
#  bibliotheque_mysql_net: